services:
  backend:
    container_name: fastapi-backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./migrations:/app/migrations

  db:
    container_name: postgresql
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_DB: ${DATABASE__DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DATABASE__USER} -d ${DATABASE__DB_NAME}
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: postgresql-admin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: shablin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
    name: postgres-volume
  pgadmin_data:
    name: pgadmin-volume